version: '3'

services:
  app:
    build:
      context: .
    image: ghcr.io/miladrahimi/shadowsocks-manager:latest
    restart: always
    network_mode: host
    volumes:
      - ./configs/:/app/configs/
      - ./storage/:/app/storage/
      - ./web/:/app/web/
