version: '3'

services:
  app:
    image: ghcr.io/getimages/shadowsocks-manager:latest
    restart: always
    volumes:
      - ./configs/:/app/configs/
      - ./storage/:/app/storage/
      - ./web/:/app/web/
    ports:
      - "${APP_EXPOSED_PORT:-80}:80"
