version: '3'

services:
  app:
    build:
      context: .
    image: ghcr.io/getimages/shadowsocks-manager:latest
    restart: always
    volumes:
      - ./configs/:/app/configs/
      - ./storage/:/app/storage/
      - ./web/:/app/web/
    ports:
      - "${APP_EXPOSED_PORT:-80}:8080"
      - "${SS_EXPOSED_PORT:-1919}:1919"
