services:
  app:
    image: ghcr.io/miladrahimi/p-manager:${TAG:-stable}
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./configs/:/app/configs/
      - ./storage/:/app/storage/
      - ./web/:/app/web/
